version: '3.8'
services:
  mlflow:
    image: python:3.8
    ports:
      - 5000:5000
    volumes:
      - ./mlflow:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://postgres:password@db/mlflow
    command: mlflow server --backend-store-uri $MLFLOW_BACKEND_STORE_URI --default-artifact-root /mlflow --host 0.0.0.0

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mlflow
